"""Seed database with realistic EMEA banks"""
from app.core.database import SessionLocal, init_db
from app.models.bank import Bank

def seed_banks():
    """Create dummy banks inspired by real EMEA institutions"""

    # Initialize database first
    init_db()

    db = SessionLocal()

    # Clear existing banks
    db.query(Bank).delete()
    db.commit()

    banks = [
        # European Banks
        Bank(
            name="Deutsche Finanzbank AG",
            short_name="DFB",
            bank_type="Commercial",
            headquarters_country="Germany",
            headquarters_city="Frankfurt",
            contact_email="syndication@dfb-bank.de",
            website="https://dfb-bank.de",
            total_assets_usd=1800000000000,
            tier1_capital_ratio=14.5,
            credit_rating="AA-",
            min_loan_amount=20000000,
            max_loan_amount=800000000,
            preferred_sectors=["Manufacturing", "Automotive", "Technology", "Renewable Energy"],
            regions_served=["Europe", "Middle East", "North America"],
            risk_appetite="Moderate",
            default_rate_percentage=0.8,
            avg_interest_rate=4.2,
            participation_count=156,
            is_active=True,
            is_verified=True,
            description="Leading German commercial bank specializing in corporate lending and syndications."
        ),
        Bank(
            name="BNP Paribas Corporate Finance",
            short_name="BNPP",
            bank_type="Investment",
            headquarters_country="France",
            headquarters_city="Paris",
            contact_email="syndications@bnpparibas.eu",
            website="https://bnpparibas.com",
            total_assets_usd=2900000000000,
            tier1_capital_ratio=13.8,
            credit_rating="AA",
            min_loan_amount=30000000,
            max_loan_amount=1000000000,
            preferred_sectors=["Finance", "Energy", "Infrastructure", "Healthcare"],
            regions_served=["Europe", "Africa", "Asia"],
            risk_appetite="Moderate",
            default_rate_percentage=0.6,
            avg_interest_rate=4.0,
            participation_count=203,
            is_active=True,
            is_verified=True,
            description="French multinational investment bank with strong presence in corporate lending."
        ),
        Bank(
            name="Barclays International Syndications",
            short_name="BARC",
            bank_type="Investment",
            headquarters_country="United Kingdom",
            headquarters_city="London",
            contact_email="loan.syndications@barclays.co.uk",
            website="https://barclays.com",
            total_assets_usd=1700000000000,
            tier1_capital_ratio=14.2,
            credit_rating="A+",
            min_loan_amount=25000000,
            max_loan_amount=750000000,
            preferred_sectors=["Technology", "Real Estate", "Consumer Goods", "Media"],
            regions_served=["Europe", "Middle East", "Africa"],
            risk_appetite="Moderate",
            default_rate_percentage=0.9,
            avg_interest_rate=4.5,
            participation_count=178,
            is_active=True,
            is_verified=True,
            description="British multinational bank with extensive syndication expertise across EMEA."
        ),

        # Middle East Banks
        Bank(
            name="Emirates Global Banking Corporation",
            short_name="EGBC",
            bank_type="Commercial",
            headquarters_country="United Arab Emirates",
            headquarters_city="Dubai",
            contact_email="corporate.lending@egbc.ae",
            website="https://egbc.ae",
            total_assets_usd=280000000000,
            tier1_capital_ratio=16.5,
            credit_rating="AA-",
            min_loan_amount=15000000,
            max_loan_amount=500000000,
            preferred_sectors=["Real Estate", "Tourism", "Energy", "Construction"],
            regions_served=["Middle East", "Asia", "Africa"],
            risk_appetite="Aggressive",
            default_rate_percentage=1.2,
            avg_interest_rate=5.0,
            participation_count=89,
            is_active=True,
            is_verified=True,
            description="Leading UAE bank specializing in regional infrastructure and development financing."
        ),
        Bank(
            name="Qatar International Finance House",
            short_name="QIFH",
            bank_type="Investment",
            headquarters_country="Qatar",
            headquarters_city="Doha",
            contact_email="syndications@qifh.qa",
            website="https://qifh.qa",
            total_assets_usd=195000000000,
            tier1_capital_ratio=17.2,
            credit_rating="AA",
            min_loan_amount=20000000,
            max_loan_amount=600000000,
            preferred_sectors=["Energy", "Infrastructure", "Finance", "Technology"],
            regions_served=["Middle East", "Europe", "Asia"],
            risk_appetite="Moderate",
            default_rate_percentage=0.7,
            avg_interest_rate=4.8,
            participation_count=67,
            is_active=True,
            is_verified=True,
            description="Qatari investment bank with focus on energy and infrastructure projects."
        ),
        Bank(
            name="Al-Mashreq Development Bank",
            short_name="AMDB",
            bank_type="Commercial",
            headquarters_country="Saudi Arabia",
            headquarters_city="Riyadh",
            contact_email="corporate@almashreq.sa",
            website="https://almashreq.sa",
            total_assets_usd=320000000000,
            tier1_capital_ratio=15.8,
            credit_rating="A+",
            min_loan_amount=25000000,
            max_loan_amount=700000000,
            preferred_sectors=["Energy", "Petrochemicals", "Mining", "Manufacturing"],
            regions_served=["Middle East", "Africa"],
            risk_appetite="Moderate",
            default_rate_percentage=0.9,
            avg_interest_rate=4.6,
            participation_count=94,
            is_active=True,
            is_verified=True,
            description="Saudi bank specializing in energy sector financing and regional development."
        ),

        # African Banks
        Bank(
            name="Standard Bank of Africa",
            short_name="SBA",
            bank_type="Commercial",
            headquarters_country="South Africa",
            headquarters_city="Johannesburg",
            contact_email="syndications@standardbank.co.za",
            website="https://standardbank.co.za",
            total_assets_usd=185000000000,
            tier1_capital_ratio=15.1,
            credit_rating="BBB+",
            min_loan_amount=10000000,
            max_loan_amount=400000000,
            preferred_sectors=["Mining", "Agriculture", "Manufacturing", "Infrastructure"],
            regions_served=["Africa", "Middle East"],
            risk_appetite="Moderate",
            default_rate_percentage=1.5,
            avg_interest_rate=6.2,
            participation_count=112,
            is_active=True,
            is_verified=True,
            description="Africa's largest bank by assets with pan-African syndication capabilities."
        ),
        Bank(
            name="Banque Africaine de Développement",
            short_name="BAD",
            bank_type="Development",
            headquarters_country="Ivory Coast",
            headquarters_city="Abidjan",
            contact_email="lending@bad-bank.ci",
            website="https://bad-bank.org",
            total_assets_usd=95000000000,
            tier1_capital_ratio=18.5,
            credit_rating="AAA",
            min_loan_amount=15000000,
            max_loan_amount=350000000,
            preferred_sectors=["Infrastructure", "Agriculture", "Renewable Energy", "Education"],
            regions_served=["Africa"],
            risk_appetite="Conservative",
            default_rate_percentage=0.3,
            avg_interest_rate=3.8,
            participation_count=78,
            is_active=True,
            is_verified=True,
            description="African development bank focused on infrastructure and sustainable development."
        ),
        Bank(
            name="Egyptian International Bank",
            short_name="EIB",
            bank_type="Commercial",
            headquarters_country="Egypt",
            headquarters_city="Cairo",
            contact_email="corporate@eib.eg",
            website="https://eib.eg",
            total_assets_usd=78000000000,
            tier1_capital_ratio=14.8,
            credit_rating="BB+",
            min_loan_amount=8000000,
            max_loan_amount=250000000,
            preferred_sectors=["Tourism", "Real Estate", "Manufacturing", "Energy"],
            regions_served=["Middle East", "Africa"],
            risk_appetite="Aggressive",
            default_rate_percentage=2.1,
            avg_interest_rate=6.8,
            participation_count=56,
            is_active=True,
            is_verified=True,
            description="Leading Egyptian bank serving North African and Middle Eastern markets."
        ),

        # Additional European Banks
        Bank(
            name="Nordea Corporate Banking",
            short_name="NORD",
            bank_type="Commercial",
            headquarters_country="Finland",
            headquarters_city="Helsinki",
            contact_email="syndications@nordea.fi",
            website="https://nordea.com",
            total_assets_usd=620000000000,
            tier1_capital_ratio=15.9,
            credit_rating="AA-",
            min_loan_amount=15000000,
            max_loan_amount=450000000,
            preferred_sectors=["Technology", "Renewable Energy", "Healthcare", "Logistics"],
            regions_served=["Europe", "Nordic Region"],
            risk_appetite="Conservative",
            default_rate_percentage=0.5,
            avg_interest_rate=3.9,
            participation_count=134,
            is_active=True,
            is_verified=True,
            description="Nordic bank with expertise in sustainable and technology sector financing."
        ),
        Bank(
            name="UniCredit Syndications Group",
            short_name="UCG",
            bank_type="Investment",
            headquarters_country="Italy",
            headquarters_city="Milan",
            contact_email="syndications@unicredit.it",
            website="https://unicredit.eu",
            total_assets_usd=980000000000,
            tier1_capital_ratio=14.3,
            credit_rating="BBB+",
            min_loan_amount=20000000,
            max_loan_amount=550000000,
            preferred_sectors=["Manufacturing", "Fashion", "Food & Beverage", "Tourism"],
            regions_served=["Europe", "Middle East"],
            risk_appetite="Moderate",
            default_rate_percentage=1.1,
            avg_interest_rate=4.7,
            participation_count=145,
            is_active=True,
            is_verified=True,
            description="Pan-European bank with strong presence in Southern and Eastern Europe."
        ),
        Bank(
            name="Santander Corporate Finance",
            short_name="SANT",
            bank_type="Commercial",
            headquarters_country="Spain",
            headquarters_city="Madrid",
            contact_email="corporate.banking@santander.es",
            website="https://santander.com",
            total_assets_usd=1650000000000,
            tier1_capital_ratio=12.9,
            credit_rating="A",
            min_loan_amount=25000000,
            max_loan_amount=700000000,
            preferred_sectors=["Automotive", "Infrastructure", "Renewable Energy", "Retail"],
            regions_served=["Europe", "Latin America", "Middle East"],
            risk_appetite="Moderate",
            default_rate_percentage=1.0,
            avg_interest_rate=4.4,
            participation_count=167,
            is_active=True,
            is_verified=True,
            description="Spanish multinational bank with global syndication capabilities."
        ),
        Bank(
            name="Rabobank International",
            short_name="RABO",
            bank_type="Commercial",
            headquarters_country="Netherlands",
            headquarters_city="Amsterdam",
            contact_email="wholesale@rabobank.nl",
            website="https://rabobank.com",
            total_assets_usd=710000000000,
            tier1_capital_ratio=16.2,
            credit_rating="AA-",
            min_loan_amount=10000000,
            max_loan_amount=400000000,
            preferred_sectors=["Agriculture", "Food & Beverage", "Logistics", "Renewable Energy"],
            regions_served=["Europe", "Africa", "Asia"],
            risk_appetite="Conservative",
            default_rate_percentage=0.6,
            avg_interest_rate=4.1,
            participation_count=98,
            is_active=True,
            is_verified=True,
            description="Dutch cooperative bank specializing in agribusiness and food sector financing."
        ),
    ]

    db.bulk_save_objects(banks)
    db.commit()

    print(f"✅ Seeded {len(banks)} EMEA banks successfully!")
    print("\nBank Summary:")
    print(f"  Europe: 7 banks")
    print(f"  Middle East: 3 banks")
    print(f"  Africa: 3 banks")
    print(f"  Total: {len(banks)} banks")

    db.close()

if __name__ == "__main__":
    seed_banks()
